In [1]:
import pickle

data_dict = pickle.load(open('/Users/joaoangnes/Documents/Faculdade/Sistema Inteligentes/Sign-Language-Detection-using-Landmarks-Python/data.pickle', 'rb'))

In [26]:
# =============== OBTER OS DADOS DO DADASET ===================
import numpy as np
import pandas as pd
import pprint
# Transformando os dados do dadaset e transformando em dataframe
# Convertendo em DataFrame
df_data = pd.DataFrame()

# # Transformando cada dados dos arrays em colunas do dataframe
for lista in data_dict['data']:
    linha_list = np.asarray(lista).reshape(-1)
    linha = pd.DataFrame([linha_list])
    df_data = pd.concat([df_data, linha], ignore_index=True)

classes_list = np.asarray(data_dict['class']) # Coleta as classes 
df_classes = pd.DataFrame(classes_list)

df_data.insert(loc=df_data.columns.get_loc(0), column='class', value=df_classes)

# Lista com os nomes das novas colunas
new_cols = []
for i in range(21):
    # new_cols.append(f'ponto {i}')
    new_cols.append(f'x{i}')
    new_cols.append(f'y{i}')

# # Renomeia as colunas do dataframe com as novas colunas coletadas
df_data.columns = ['class'] + new_cols
df_data

,class,x0,y0,x1,y1,x2,y2,x3,y3,x4,...,x16,y16,x17,y17,x18,y18,x19,y19,x20,y20
0,18,106,431,140,413,154,375,126,347,97,...,100,367,71,352,61,337,75,360,88,378
1,18,279,396,240,388,205,356,197,326,218,...,231,326,297,312,269,305,255,330,253,353
2,18,225,282,260,274,285,241,276,209,259,...,240,214,204,204,211,189,219,213,224,233
3,18,511,336,482,309,472,265,496,234,528,...,525,245,545,258,553,242,539,259,528,277
4,18,308,269,273,260,244,225,243,191,267,...,279,175,334,196,318,177,300,196,293,220
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5963,14,326,272,357,280,399,253,404,218,391,...,356,226,318,186,338,185,336,216,331,239
5964,14,74,449,110,440,132,409,119,375,95,...,93,384,65,372,68,354,74,377,80,396
5965,14,289,267,319,276,358,252,360,219,346,...,312,228,278,188,292,186,291,216,290,237
5966,14,505,327,476,313,460,279,478,249,504,...,497,265,518,259,519,244,514,260,508,275
5967,14,477,379,445,365,426,333,444,308,468,...,464,321,490,308,488,294,482,311,477,325

In [10]:
# ============= BALANCEAMENTO =================

# Como o dataset foi criado de forma balanceada o dataset nÃ£o precisa ser tratado, pois jÃ¡ estÃ¡ balanceado
df_data['class'].sort_values().value_counts()

0     300
16    300
8     300
5     300
4     300
19    300
1     300
17    300
18    300
14    300
13    300
9     300
12    299
6     299
7     298
3     297
15    295
11    294
2     293
10    293
Name: class, dtype: int64

In [13]:
# Balancear os dados
from imblearn.over_sampling import SMOTE

# Segmentar os dados
df_atributos = df_data.drop(columns=['class'])
df_classes = df_data['class']

# dados_atributos.columns

resampler = SMOTE()
df_atributos, df_classes = resampler.fit_resample(df_atributos, df_classes)

df_classes.value_counts()

18    300
9     300
5     300
13    300
2     300
12    300
3     300
15    300
4     300
8     300
19    300
10    300
1     300
17    300
6     300
16    300
7     300
11    300
0     300
14    300
Name: class, dtype: int64

In [14]:
# ========= NORMALIZCÃƒO DOS DADOS ========================
from sklearn import preprocessing 
normalizer = preprocessing.MinMaxScaler()

# df_atributos = df_data.drop(columns=['class'])
# df_classes = df_data['class']

# Modelo para normalizar os dados nÃºmericos
normalization_model = normalizer.fit(df_atributos) # NÃ£o normalizar as classes - drop da coluba class antes desta linha

from pickle import dump
dump(normalization_model, open('/Users/joaoangnes/Documents/Faculdade/Sistema Inteligentes/Sign-Language-Detection-using-Landmarks-Python/normalization.model', 'wb'))

dt_num_normalized = normalization_model.fit_transform(df_atributos)

df_atributos = pd.DataFrame(dt_num_normalized, columns=df_atributos.columns)

df_data_normalized = df_atributos.join(df_classes, how = 'left')

df_atributos

,x0,y0,x1,y1,x2,y2,x3,y3,x4,y4,...,x16,y16,x17,y17,x18,y18,x19,y19,x20,y20
0,0.132216,0.838875,0.133630,0.837398,0.148585,0.777143,0.101545,0.734139,0.069583,0.714697,...,0.167549,0.764988,0.080645,0.772595,0.083045,0.670455,0.096386,0.742021,0.119932,0.813953
1,0.454376,0.749361,0.356347,0.769648,0.268868,0.722857,0.258278,0.670695,0.310139,0.645533,...,0.398589,0.666667,0.485663,0.655977,0.442907,0.579545,0.406196,0.662234,0.398649,0.749354
2,0.353818,0.457801,0.400891,0.460705,0.457547,0.394286,0.432671,0.317221,0.391650,0.291066,...,0.414462,0.398082,0.318996,0.341108,0.342561,0.250000,0.344234,0.351064,0.349662,0.439276
3,0.886406,0.595908,0.895323,0.555556,0.898585,0.462857,0.918322,0.392749,0.926441,0.394813,...,0.917108,0.472422,0.930108,0.498542,0.934256,0.400568,0.895009,0.473404,0.863176,0.552972
4,0.508380,0.424552,0.429844,0.422764,0.360849,0.348571,0.359823,0.262840,0.407555,0.256484,...,0.483245,0.304556,0.551971,0.317784,0.527682,0.215909,0.483649,0.305851,0.466216,0.405685
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,0.186220,0.685422,0.195991,0.707317,0.242925,0.700000,0.302428,0.712991,0.345924,0.700288,...,0.405644,0.621103,0.268817,0.679300,0.339100,0.571023,0.356282,0.595745,0.373311,0.638243
5996,0.493482,0.516624,0.554566,0.563686,0.625000,0.562857,0.653422,0.564955,0.666004,0.559078,...,0.691358,0.505995,0.521505,0.469388,0.574394,0.392045,0.595525,0.430851,0.611486,0.483204
5997,0.692737,0.335038,0.652561,0.325203,0.615566,0.271429,0.580574,0.199396,0.538767,0.187320,...,0.700176,0.328537,0.715054,0.239067,0.711073,0.136364,0.686747,0.226064,0.677365,0.299742
5998,0.716946,0.797954,0.674833,0.853659,0.599057,0.834286,0.545254,0.797583,0.512922,0.737752,...,0.698413,0.812950,0.688172,0.734694,0.666090,0.576705,0.640275,0.545213,0.618243,0.534884
5999,0.456238,0.265985,0.521158,0.241192,0.584906,0.165714,0.596026,0.087613,0.576541,0.060519,...,0.511464,0.282974,0.431900,0.137026,0.437716,0.002841,0.425129,0.002660,0.422297,0.002584

In [15]:
########################
# - HIPERPARAMETERS 
# Usando Random Forest

from sklearn.ensemble import RandomForestClassifier
from pprint import pprint
rf = RandomForestClassifier(random_state = 42)

pprint(rf.get_params())

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 42,
 'verbose': 0,
 'warm_start': False}

In [19]:
import numpy as np

# Determinar as faixas de valores para cada hiperparemtro
n_estimators = [int(x) for x in np.linspace(start=10, stop=300, num=10)]
criterion = ['gini', 'entropy']
min_samples_split = [int(x) for x in np.linspace(start=2, stop=10, num=3)]
max_depth = [int(x) for x in np.linspace(start=10, stop=100, num=10)]
max_features = ['sqrt', 'log2']

# Criar a grade de valores
rf_grid = {
    'n_estimators' : n_estimators,
    'criterion' : criterion,
    'min_samples_split' : min_samples_split,
    'max_depth' : max_depth,
    'max_features' : max_features,
    'random_state': [42]
}

pprint(rf_grid)

{'criterion': ['gini', 'entropy'],
 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
 'max_features': ['sqrt', 'log2'],
 'min_samples_split': [2, 6, 10],
 'n_estimators': [10, 42, 74, 106, 138, 171, 203, 235, 267, 300],
 'random_state': [42]}

In [20]:
# Rodar o GridSearch (treinamento e avaliaÃ§Ã£o do grid)
from sklearn.model_selection import RandomizedSearchCV

# rf = RandomForestClassifier()
rf_hyperparameters = RandomizedSearchCV(
                                        estimator = rf,
                                        param_distributions = rf_grid,
                                        n_iter = 500,
                                        cv = 20,
                                        verbose = 1,
                                        random_state = 42,
                                        n_jobs = -1
                                        )
df_atributos = df_data_normalized.drop(columns=['class'])
df_classes = df_data_normalized['class']

# rf_hyperparameters.fit(df_atributos, df_classes.values.ravel())
rf_hyperparameters.fit(df_atributos, df_classes)
pprint(rf_hyperparameters.best_params_)

Fitting 20 folds for each of 500 candidates, totalling 10000 fits
{'criterion': 'gini',
 'max_depth': 60,
 'max_features': 'sqrt',
 'min_samples_split': 2,
 'n_estimators': 203,
 'random_state': 42}

In [21]:
# ============== TREINAMENTO =================
# Treinar o modelo de ML

# print(df_classes.values.ravel())

rf = RandomForestClassifier(**rf_hyperparameters.best_params_)
# fertility_rf = rf.fit(df_atributos, df_classes.values.ravel())
fertility_rf = rf.fit(df_atributos, df_classes)
pprint(fertility_rf)

RandomForestClassifier(max_depth=60, n_estimators=203, random_state=42)

In [22]:
from sklearn.model_selection import cross_validate

scoring = ['precision_macro', 'recall_macro']
scores_cross = cross_validate(rf, df_atributos, df_classes, cv=10, scoring = scoring) # Rodar Cross Validation
print('Matriz de sensibilidades:', scores_cross['test_precision_macro'])
print('Matriz de especificidades:', scores_cross['test_recall_macro'])

# Metricas finais
print('Especificade:', scores_cross['test_precision_macro'].mean())
print('Sensibilidades:', scores_cross['test_recall_macro'].mean())

Matriz de sensibilidades: [0.92865508 0.94816087 0.95903084 0.94234831 0.95599414 0.96759767
 0.95747282 0.96462888 0.9642069  0.96552815]
Matriz de especificidades: [0.925      0.94666667 0.95666667 0.94       0.955      0.96666667
 0.955      0.96333333 0.96166667 0.96333333]
Especificade: 0.9553623662330274
Sensibilidades: 0.9533333333333334

In [23]:
import pickle

f = open('model.p', 'wb')
pickle.dump({'model': fertility_rf}, f)
f.close()

In [24]:
df_data_denormalized = pd.DataFrame( normalization_model.inverse_transform(df_atributos), columns=df_atributos.columns)
df_data_denormalized

,x0,y0,x1,y1,x2,y2,x3,y3,x4,y4,...,x16,y16,x17,y17,x18,y18,x19,y19,x20,y20
0,106.0,431.0,140.0,413.0,154.0,375.0,126.0,347.0,97.0,336.0,...,100.0,367.0,71.0,352.0,61.0,337.0,75.0,360.0,88.0,378.0
1,279.0,396.0,240.0,388.0,205.0,356.0,197.0,326.0,218.0,312.0,...,231.0,326.0,297.0,312.0,269.0,305.0,255.0,330.0,253.0,353.0
2,225.0,282.0,260.0,274.0,285.0,241.0,276.0,209.0,259.0,189.0,...,240.0,214.0,204.0,204.0,211.0,189.0,219.0,213.0,224.0,233.0
3,511.0,336.0,482.0,309.0,472.0,265.0,496.0,234.0,528.0,225.0,...,525.0,245.0,545.0,258.0,553.0,242.0,539.0,259.0,528.0,277.0
4,308.0,269.0,273.0,260.0,244.0,225.0,243.0,191.0,267.0,177.0,...,279.0,175.0,334.0,196.0,318.0,177.0,300.0,196.0,293.0,220.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,135.0,371.0,168.0,365.0,194.0,348.0,217.0,340.0,236.0,331.0,...,235.0,307.0,176.0,320.0,209.0,302.0,226.0,305.0,238.0,310.0
5996,300.0,305.0,329.0,312.0,356.0,300.0,376.0,291.0,397.0,282.0,...,397.0,259.0,317.0,248.0,345.0,239.0,365.0,243.0,379.0,250.0
5997,407.0,234.0,373.0,224.0,352.0,198.0,343.0,170.0,333.0,153.0,...,402.0,185.0,425.0,169.0,424.0,149.0,418.0,166.0,418.0,179.0
5998,420.0,415.0,383.0,419.0,345.0,395.0,327.0,368.0,320.0,344.0,...,401.0,387.0,410.0,339.0,398.0,304.0,391.0,286.0,383.0,270.0
5999,280.0,207.0,314.0,193.0,339.0,161.0,350.0,133.0,352.0,109.0,...,295.0,166.0,267.0,134.0,266.0,102.0,266.0,82.0,267.0,64.0